services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_admin
      POSTGRES_DB: crypto_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crypto_database
      SPRING_DATASOURCE_USERNAME: db_admin
      SPRING_DATASOURCE_PASSWORD: db_admin
    depends_on:
      - db



volumes:
  postgres_data: